---
#
# Database
#
- name: "Container Database"
  community.docker.docker_container:
    name: "{{ composeProjectName }}-front"
    image: "{{ mailu_image_base }}/nginx:{{ mailu_tag }}"
    env_file: ./mailu/.env
    restart_policy: unless-stopped
    #recreate: true
    hostname: front
    log_driver: journald
    log_options:
      tag: "{{ composeProjectName }}-front"
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "110:110"
      - "995:995"
      - "143:143"
      - "993:993"
    networks:
      - name: mailu
      - name: webmail
      - name: radicale
      - name: proxy
    volumes:
      - "./mailu/certs:/certs"
    dns_servers:
      - 172.23.0.254
