---
# YouTrack Containers
#
# YouTrack
- name: Container YouTrack
  community.docker.docker_container:
    name: youtrack-app
    image: "{{ youtrack_image }}:{{ youtrack_tag }}"
    restart_policy: unless-stopped
    #env_file: ./youtrack/youtrack.env
    volumes:
    - ./youtrack/data:/opt/youtrack/data
    - ./youtrack/logs:/opt/youtrack/logs
    - ./youtrack/conf:/opt/youtrack/conf
    - ./youtrack/backups:/opt/youtrack/backups
    memory: 2G
    networks:
      - name: proxy