---
- name: Check if directory exists
  stat:
    path: ./youtrack/
  register: main_directory

- name: Prepare main directory
  ansible.builtin.file:
    path: "./youtrack/{{ item }}/"
    state: directory
    owner: optiwi
    recurse: yes
  loop:
    - backups
    - conf
    - data
    - logs
  when: not main_directory.stat.exists

- name: Set directory permissions
  ansible.builtin.file:
    path: "./youtrack/{{ item }}"
    owner: 13001
    group: 13001
    recurse: true
  loop:
    - backups
    - conf
    - data
    - logs
  become: true

#- name: Copy environment files
#  ansible.builtin.template:
#    src: "{{ item }}.j2"
#    dest: "./nextcloud/{{ item }}"
#    owner: optiwi
#    mode: '0644'
#  loop:
#    - database.env
#    - nextcloud.env

#- name: Copy database config file
#  ansible.builtin.copy:
#    src: mysql-config.cnf
#    dest: ./nextcloud/mysql-config.cnf
#    owner: optiwi
#    mode: '0644'