---
# tasks file for caddy
- name: Install/Update Role
  when: role_state == "present"
  include_tasks: install.yml

- name: Uninstall Role
  when: role_state == "absent"
  include_tasks: uninstall.yml