- name: Running container Redis
  community.docker.docker_container:
    name: "{{ composeProjectName }}-redis"
    image: "{{ redis_image }}"
    command: --save 60 1 --loglevel warning
    restart_policy: unless-stopped
    hostname: redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./mailu/redis:/data
    networks:
      - name: mailu
    dns_servers:
      - 172.23.0.254