---
# Authentik Containers
#
# Redis
- name: Running Redis
  community.docker.docker_container:
    name: authentik-cache
    image: "{{ redis_image }}:{{ redis_tag }}"
    command: --save 60 1 --loglevel warning
    restart_policy: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./authentik/redis:/data
    networks:
      - name: authentik

# PostgreSQL
- name: Running PostgreSQL
  community.docker.docker_container:
    name: authentik-database
    image: "{{ postgres_image }}:{{ postgres_tag }}"
    restart_policy: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./authentik/postgres:/var/lib/postgresql/data
    networks:
      - name: authentik
    env:
      POSTGRES_PASSWORD: "{{ postgres_password }}"
      POSTGRES_USER: "{{ postgres_user }}"
      POSTGRES_DB: "{{ postgres_database }}"

# Authentik Server
- name: Running Authentik Server 
  community.docker.docker_container:
    name: authentik-server
    image: "{{ authentik_image }}:{{ authentik_tag }}"
    command: server
    restart_policy: unless-stopped
    volumes:
      - ./authentik/media:/media
      - ./authentik/custom-templates:/templates
    networks:
      - name: authentik
      - name: proxy
    env_file: ./authentik/.env

# Authentik Worker
- name: Running Authentik Worker
  community.docker.docker_container:
    name: authentik-worker
    image: "{{ authentik_image }}:{{ authentik_tag }}"
    command: worker
    restart_policy: unless-stopped
    recreate: true
    volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock
      - ./authentik/media:/media
      - ./authentik/custom-templates:/templates
      - ./authentik/certs:/certs
      - ./authentik/icon_left_brand.png:/web/dist/assets/icons/icon_left_brand.png:ro
    networks:
      - name: authentik
      - name: proxy
    env_file: ./authentik/.env