---
# tasks file for authentik
- name: Install/Update Authentik
  when: role_state == "present"
  include_tasks: install.yml

- name: Remove Authentik
  when: role_state == "absent"
  include_tasks: uninstall.yml