---
- name: Pulling images
  community.docker.docker_image_pull:
    name: "{{ item }}"
  loop:
    - "{{ mariadb_image }}:{{ mariadb_tag }}"
    - "{{ redis_image }}:{{ redis_tag }}"
    - "{{ erpnext_image }}:{{ erpnext_tag }}"