---
# tasks file for directus
- name: Install/Update Directus
  when: role_state == "present"
  include_tasks: install.yml

- name: Remove Directus
  when: role_state == "absent"
  include_tasks: uninstall.yml