---
- name: Check if secrets file already exists
  ansible.builtin.stat:
    path: ./{{ role_id }}/secrets
  register: secrets_file

- name: Save password store
  vars:
    generatedPasswords:
      - "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits']) }}"
      - "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits']) }}"
      - "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_letters', 'digits']) }}"
  ansible.builtin.copy:
    dest: "./{{ role_id }}/secrets"
    content: "{{ generatedPasswords | to_json }}"
  when: not secrets_file.stat.exists

- name: Load password store
  command: "cat ./{{ role_id }}/secrets"
  register: password_store

- ansible.builtin.set_fact:
    secrets: "{{ password_store.stdout | from_json }}"

- ansible.builtin.set_fact:
    mariadbRootPassword: "{{ secrets[0] }}"
    mysqlPassword: "{{ secrets[1] }}"
    directusSecret: "{{ secrets[2] }}"